DROP DATABASE IF EXISTS restaurant_db;
CREATE DATABASE restaurant_db;
USE restaurant_db;

INSERT INTO customers (name,street,exterior,interior,zipCode,province,city,state,email,phoneNumber,createdAt,updatedAt) VALUES ('Francisco Silva','Viveros','123','123','03000','Mexico','Mexico','Distrito Federal','test@gmail.com','5555555555',sysdate(),sysdate());
INSERT INTO foods (FoodName,FoodType,Category,Price,Picture,createdAt,updatedAt) values ("Sopa de Fideo","comida","entrada",20,"../assets/images/comida/sopa-de-fideo.jpg",sysdate(),sysdate());
INSERT INTO foods (FoodName,FoodType,Category,Price,Picture,createdAt,updatedAt) values ("ConsomÈ de pollo","comida","entrada",20,"../assets/images/comida/consome-de-pollo.jpg",sysdate(),sysdate());
INSERT INTO foods (FoodName,FoodType,Category,Price,Picture,createdAt,updatedAt) values ("Crema de verduras","comida","entrada",20,"../assets/images/comida/crema-de-verduras.jpg",sysdate(),sysdate());
INSERT INTO foods (FoodName,FoodType,Category,Price,Picture,createdAt,updatedAt) values ("Lentejas","comida","entrada",20,"../assets/images/comida/sopa-de-lentejas.jpg",sysdate(),sysdate());
INSERT INTO foods (FoodName,FoodType,Category,Price,Picture,createdAt,updatedAt) values ("Arroz a la mexicana","comida","guarnicion",20,"../assets/images/comida/arroz-a-la-mexicana.jpg",sysdate(),sysdate());
INSERT INTO foods (FoodName,FoodType,Category,Price,Picture,createdAt,updatedAt) values ("Spaguetti rojo","comida","guarnicion",20,"../assets/images/comida/spaguetti.jpg",sysdate(),sysdate());
INSERT INTO foods (FoodName,FoodType,Category,Price,Picture,createdAt,updatedAt) values ("Ensalada de Lechuga","comida","guarnicion",20,"../assets/images/comida/ensalada-de-lechuga.jpg",sysdate(),sysdate());
INSERT INTO foods (FoodName,FoodType,Category,Price,Picture,createdAt,updatedAt) values ("Frijoles charros","comida","guarnicion",20,"../assets/images/comida/frijoles-charros.jpg",sysdate(),sysdate());
INSERT INTO foods (FoodName,FoodType,Category,Price,Picture,createdAt,updatedAt) values ("Albondigas de res","comida","platillo",30,"../assets/images/comida/albondigas-de-res.jpg",sysdate(),sysdate());
INSERT INTO foods (FoodName,FoodType,Category,Price,Picture,createdAt,updatedAt) values ("Tortitas de pollo","comida","platillo",30,"../assets/images/comida/tortitas-de-pollo.jpg",sysdate(),sysdate());
INSERT INTO foods (FoodName,FoodType,Category,Price,Picture,createdAt,updatedAt) values ("Pescado empanizado","comida","platillo",40,"../assets/images/comida/pescado-empanizado.jpg",sysdate(),sysdate());
INSERT INTO foods (FoodName,FoodType,Category,Price,Picture,createdAt,updatedAt) values ("Alambre de champiÒones","comida","platillo",40,"../assets/images/comida/alambre-champiniones.jpg",sysdate(),sysdate());
INSERT INTO foods (FoodName,FoodType,Category,Price,Picture,createdAt,updatedAt) values ("Fresas con Crema","comida","postre",15,"../assets/images/comida/fresas-con-crema.jpg",sysdate(),sysdate());
INSERT INTO foods (FoodName,FoodType,Category,Price,Picture,createdAt,updatedAt) values ("Pay de limÛn","comida","postre",15,"../assets/images/comida/pay-de-limon.jpg",sysdate(),sysdate());
INSERT INTO foods (FoodName,FoodType,Category,Price,Picture,createdAt,updatedAt) values ("Gelatina","comida","postre",15,"../assets/images/comida/gelatina.jpeg",sysdate(),sysdate());
INSERT INTO foods (FoodName,FoodType,Category,Price,Picture,createdAt,updatedAt) values ("Tapioca","comida","postre",15,"../assets/images/comida/tapioca.jpg",sysdate(),sysdate());
INSERT INTO foods (FoodName,FoodType,Category,Price,Picture,createdAt,updatedAt) values ("Agua de jamaica","comida","bebida",7,"../assets/images/comida/agua-jamaica.jpg",sysdate(),sysdate());
INSERT INTO foods (FoodName,FoodType,Category,Price,Picture,createdAt,updatedAt) values ("Agua de limÛn","comida","bebida",7,"../assets/images/comida/agua-limon.jpg",sysdate(),sysdate());
INSERT INTO foods (FoodName,FoodType,Category,Price,Picture,createdAt,updatedAt) values ("Agua de horchata","comida","bebida",7,"../assets/images/comida/agua-horchata.jpg",sysdate(),sysdate());
INSERT INTO foods (FoodName,FoodType,Category,Price,Picture,createdAt,updatedAt) values ("Agua de tamarindo","comida","bebida",7,"../assets/images/comida/agua-tamarindo.jpg",sysdate(),sysdate());
INSERT INTO foods (FoodName,FoodType,Category,Price,Picture,createdAt,updatedAt) values ("Pan","comida","complemento",0,"../assets/images/comida/pan.jpeg",sysdate(),sysdate());
INSERT INTO foods (FoodName,FoodType,Category,Price,Picture,createdAt,updatedAt) values ("Tortillas","comida","complemento",0,"../assets/images/comida/tortillas.jpg",sysdate(),sysdate());
INSERT INTO foods (FoodName,FoodType,Category,Price,Picture,createdAt,updatedAt) values ("Cubiertos","comida","complemento",0,"../assets/images/comida/cubiertos.jpg",sysdate(),sysdate());
INSERT INTO foods (FoodName,FoodType,Category,Price,Picture,createdAt,updatedAt) values ("LimÛn","comida","complemento",0,"../assets/images/comida/limon.jpg",sysdate(),sysdate());

INSERT INTO foods (FoodName,FoodType,Category,Price,Picture,createdAt,updatedAt) values ("Sopa de Fideo","vegetariana","entrada",20,"../assets/images/comida/sopa-de-fideo.jpg",sysdate(),sysdate());
INSERT INTO foods (FoodName,FoodType,Category,Price,Picture,createdAt,updatedAt) values ("Lentejas","vegetariana","entrada",20,"../assets/images/comida/consome-de-pollo.jpg",sysdate(),sysdate());
INSERT INTO foods (FoodName,FoodType,Category,Price,Picture,createdAt,updatedAt) values ("Arroz a la mexicana","vegetariana","guarnicion",20,"../assets/images/comida/arroz-a-la-mexicana.jpg",sysdate(),sysdate());
INSERT INTO foods (FoodName,FoodType,Category,Price,Picture,createdAt,updatedAt) values ("Spaguetti rojo","vegetariana","guarnicion",20,"../assets/images/comida/spaguetti.jpg",sysdate(),sysdate());
INSERT INTO foods (FoodName,FoodType,Category,Price,Picture,createdAt,updatedAt) values ("Ensalada de Lechuga","vegetariana","guarnicion",20,"../assets/images/comida/ensalada-de-lechuga.jpg",sysdate(),sysdate());
INSERT INTO foods (FoodName,FoodType,Category,Price,Picture,createdAt,updatedAt) values ("Burrito vegetariano","vegetariana","platillo",40,"../assets/images/vegetariano/burrito.jpg",sysdate(),sysdate());
INSERT INTO foods (FoodName,FoodType,Category,Price,Picture,createdAt,updatedAt) values ("Lasagna vegetariana","vegetariana","platillo",40,"../assets/images/vegetariano/lasagna-vegetariana.jpg",sysdate(),sysdate());
INSERT INTO foods (FoodName,FoodType,Category,Price,Picture,createdAt,updatedAt) values ("Enchiladas vegetarianas","vegetariana","platillo",40,"../assets/images/vegetariano/enchiladas-vegetarianas.jpg",sysdate(),sysdate());
INSERT INTO foods (FoodName,FoodType,Category,Price,Picture,createdAt,updatedAt) values ("Chile relleno vegetariano","vegetariana","platillo",40,"../assets/images/vegetariano/chile-relleno-vegetariano.jpg",sysdate(),sysdate());
INSERT INTO foods (FoodName,FoodType,Category,Price,Picture,createdAt,updatedAt) values ("Gelatina","vegetariana","postre",15,"../assets/images/comida/gelatina.jpeg",sysdate(),sysdate());
INSERT INTO foods (FoodName,FoodType,Category,Price,Picture,createdAt,updatedAt) values ("Tapioca","vegetariana","postre",15,"../assets/images/comida/tapioca.jpg",sysdate(),sysdate());
INSERT INTO foods (FoodName,FoodType,Category,Price,Picture,createdAt,updatedAt) values ("Agua de jamaica","vegetariana","bebida",7,"../assets/images/comida/agua-jamaica.jpg",sysdate(),sysdate());
INSERT INTO foods (FoodName,FoodType,Category,Price,Picture,createdAt,updatedAt) values ("Agua de limÛn","vegetariana","bebida",7,"../assets/images/comida/agua-limon.jpg",sysdate(),sysdate());
INSERT INTO foods (FoodName,FoodType,Category,Price,Picture,createdAt,updatedAt) values ("Agua de horchata","vegetariana","bebida",7,"../assets/images/comida/agua-horchata.jpg",sysdate(),sysdate());
INSERT INTO foods (FoodName,FoodType,Category,Price,Picture,createdAt,updatedAt) values ("Agua de tamarindo","vegetariana","bebida",7,"../assets/images/comida/agua-tamarindo.jpg",sysdate(),sysdate());
INSERT INTO foods (FoodName,FoodType,Category,Price,Picture,createdAt,updatedAt) values ("Pan","vegetariana","complemento",0,"../assets/images/comida/pan.jpeg",sysdate(),sysdate());
INSERT INTO foods (FoodName,FoodType,Category,Price,Picture,createdAt,updatedAt) values ("Tortillas","vegetariana","complemento",0,"../assets/images/comida/tortillas.jpg",sysdate(),sysdate());
INSERT INTO foods (FoodName,FoodType,Category,Price,Picture,createdAt,updatedAt) values ("Cubiertos","vegetariana","complemento",0,"../assets/images/comida/cubiertos.jpg",sysdate(),sysdate());
INSERT INTO foods (FoodName,FoodType,Category,Price,Picture,createdAt,updatedAt) values ("LimÛn","vegetariana","complemento",0,"../assets/images/comida/limon.jpg",sysdate(),sysdate());

INSERT INTO orderheaders (OrderStatus,CustomerId,createdAt,updatedAt) values ("Entregado",1,sysdate(),sysdate());
INSERT INTO orderheaders (OrderStatus,CustomerId,createdAt,updatedAt) values ("Entregado",1,sysdate(),sysdate());
INSERT INTO orderheaders (OrderStatus,CustomerId,createdAt,updatedAt) values ("Entregado",1,sysdate(),sysdate());
INSERT INTO orderheaders (OrderStatus,CustomerId,createdAt,updatedAt) values ("Entregado",1,sysdate(),sysdate());
INSERT INTO orderheaders (OrderStatus,CustomerId,createdAt,updatedAt) values ("En Proceso",1,sysdate(),sysdate());
INSERT INTO orderlines (orderPrice,createdAt,updatedAt,FoodId,OrderHeaderId) values (45,sysdate(),sysdate(),1,1);
INSERT INTO orderlines (orderPrice,createdAt,updatedAt,FoodId,OrderHeaderId) values (45,sysdate(),sysdate(),1,2);
INSERT INTO orderlines (orderPrice,createdAt,updatedAt,FoodId,OrderHeaderId) values (45,sysdate(),sysdate(),1,3);
INSERT INTO orderlines (orderPrice,createdAt,updatedAt,FoodId,OrderHeaderId) values (45,sysdate(),sysdate(),1,4);
INSERT INTO orderlines (orderPrice,createdAt,updatedAt,FoodId,OrderHeaderId) values (45,sysdate(),sysdate(),1,5);
INSERT INTO foods (FoodName,FoodType,Category,Price,Picture,createdAt,updatedAt) values ("Chilaquiles","desayuno","platillo",50,"../assets/images/desayunos/chilaquiles-rojos.jpg",sysdate(),sysdate());
INSERT INTO foods (FoodName,FoodType,Category,Price,Picture,createdAt,updatedAt) values ("Sopes","desayuno","platillo",20,"../assets/images/desayunos/sopes.jpg",sysdate(),sysdate());
INSERT INTO foods (FoodName,FoodType,Category,Price,Picture,createdAt,updatedAt) values ("Ensalada de yogurt","desayuno","platillo",35,"../assets/images/desayunos/ensalada-yogurt.jpg",sysdate(),sysdate());
INSERT INTO foods (FoodName,FoodType,Category,Price,Picture,createdAt,updatedAt) values ("Quesadillas","desayuno","platillo",60,"../assets/images/desayunos/quesadillas.jpg",sysdate(),sysdate());
INSERT INTO foods (FoodName,FoodType,Category,Price,Picture,createdAt,updatedAt) values ("Hot Cakes","desayuno","platillo",60,"../assets/images/desayunos/hot-cakes.jpg",sysdate(),sysdate());
INSERT INTO foods (FoodName,FoodType,Category,Price,Picture,createdAt,updatedAt) values ("Pan francés de jamón","desayuno","platillo",60,"../assets/images/desayunos/pan-frances-salado.jpg",sysdate(),sysdate());
INSERT INTO foods (FoodName,FoodType,Category,Price,Picture,createdAt,updatedAt) values ("Café","desayuno","bebida",15,"../assets/images/desayunos/cafe.jpg",sysdate(),sysdate());
INSERT INTO foods (FoodName,FoodType,Category,Price,Picture,createdAt,updatedAt) values ("Jugo de naranja","desayuno","bebida",15,"../assets/images/desayunos/jugo-de-naranja.jpg",sysdate(),sysdate());
commit;